version: '3.7'

services:
  app:
    container_name: rest-user-store
    build:
      context: .
      dockerfile: app.dockerfile
    image: zamirka/rest-user-store
    ports:
      - "8080:8080"
    env_file:
      - app.env
    volumes:
      - ..:/go/src
    entrypoint:
      - go
      - run
      - /go/src/cmd/app/main.go
    networks:
      - rest-user-network
  mongo:
    container_name: rest-user-mongo
    image: mongo:3.4.18-jessie
    env_file:
      - mongo.env
    networks:
      - rest-user-network
  mongo-express:
      container_name: rest-user-mongo-e
      image: mongo-express:0.49.0
      ports:
        - "8081:8081"
      env_file:
        - mongo-express.env
      networks:
      - rest-user-network
networks: 
  rest-user-network:
    driver: bridge
